import { DEFAULT_HANDLE, DEFAULT_SLOTS, RECIPE_SLIDES } from "./fixtures";
import { normalizePayload } from "./lib";
import type { StudioState } from "./types";

export const DEFAULT_STATE: StudioState = {
  recipe: "wide-pan",
  payload: normalizePayload({
    p: 2,
    h: DEFAULT_HANDLE,
    s: RECIPE_SLIDES,
  }),
  slots: [...DEFAULT_SLOTS],
  kpis: 3,
  style: "liquid",
  kpi: "ring",
  panel: "outline",
  inset: 16,
  plane: "dusk",
  blur: 0,
  radius: 26,
  fill: 0.8,
  chart: "#475569",
  text: "",
  ink: "scrim",
  scrim: 62,
  scrimh: 68,
  shadow: 45,
  shadowb: 24,
  cpad: 28,
  mode: "dark",
  flow: false,
  frame: "ig-square",
  res: 2,
  pad: 24,
  gap: 24,
  nums: true,
  dots: true,
  arrow: true,
  safe: false,
  shot: null,
  shotName: null,
};

export const DEFAULT_QUERY = {
  recipe: DEFAULT_STATE.recipe,
  style: DEFAULT_STATE.style,
  kpi: DEFAULT_STATE.kpi,
  panel: DEFAULT_STATE.panel,
  inset: String(DEFAULT_STATE.inset),
  kpis: String(DEFAULT_STATE.kpis),
  slots: DEFAULT_STATE.slots.join(","),
  plane: DEFAULT_STATE.plane,
  blur: String(DEFAULT_STATE.blur),
  radius: String(DEFAULT_STATE.radius),
  frame: DEFAULT_STATE.frame,
  res: String(DEFAULT_STATE.res),
  pad: String(DEFAULT_STATE.pad),
  gap: String(DEFAULT_STATE.gap),
  fill: String(DEFAULT_STATE.fill),
  chart: DEFAULT_STATE.chart,
  text: DEFAULT_STATE.text,
  ink: DEFAULT_STATE.ink,
  scrim: String(DEFAULT_STATE.scrim),
  scrimh: String(DEFAULT_STATE.scrimh),
  shadow: String(DEFAULT_STATE.shadow),
  shadowb: String(DEFAULT_STATE.shadowb),
  cpad: String(DEFAULT_STATE.cpad),
  mode: DEFAULT_STATE.mode,
  flow: String(DEFAULT_STATE.flow),
  nums: String(DEFAULT_STATE.nums),
  dots: String(DEFAULT_STATE.dots),
  arrow: String(DEFAULT_STATE.arrow),
  safe: String(DEFAULT_STATE.safe),
};
